version: '3'
services:
  gpsserver:
    build: gps
    ports:
      - "3000:3000"
  
  mavserver:
    build: mavlink
    ports:
      - "4000:4000"

  webserver:
    build: webxr
    ports:
      - "8000:8000"
