version: '3'
services:
  gps:
    build: gps
    ports:
      - "3000:3000"
  
  mav:
    build: mavlink
    ports:
      - "4000:4000"

  web:
    build: webxr
    ports:
      - "8000:8000"
    environment:
      - GPS_POSITION_URL=http://gps:3000/position
