version: '3'
services:
  gps:
    build: gps
    ports:
      - "3000:3000"
  
  mav:
    build: mavlink
    ports:
      - "4000:4000"
    # devices:
      # - "/dev/ttyUSB0"
    environment:
      # - MAVLINK_URL=serial:///dev/ttyUSB0:57600?ids=200,1
      - MAVLINK_URL=tcp://sitl:5760?ids=200,1

  web:
    build: webxr
    ports:
      - "8000:8000"
    environment:
      # - GPS_HOST=gps:3000
      - GPS_HOST=192.168.111.1:3000
      - MAV_HOST=mav:4000
  
  sitl:
    image: uobflightlabstarling/starling-sim-ardupilot-plane
    ports:
      - "5760:5760"
      - "5762:5762"
    environment:
      - AP_HOME=52.818,-4.125,34.77,0
